In [1]:
import numpy as np

M = 5
N = 6

# Create MxN table filled with random integers between 1 and 100
table = np.random.randint(1, 100, size=(M, N))

# Print out the third row
print(table[2])

# Print out the third column
print(table[:, 2])

# Set every element in the last row equal to 7
table[-1, :] = 7

# Set every element in the last column equal to the sum of the first two columns
first_two_cols_sum = table[:, :2].sum(axis=1)
table[:, -1] = first_two_cols_sum

print(table)


[78 10 21 67 63 40]
[73 89 21  4 12]
[[  8  12  73  94  57  20]
 [ 53  71  89  77  68 124]
 [ 78  10  21  67  63  88]
 [ 43  59   4  76  76 102]
 [  7   7   7   7   7  14]]
